# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hero_name', models.CharField(max_length=255, unique=True, verbose_name='Hero name')),
                ('real_name', models.CharField(max_length=255, verbose_name='Real name')),
                ('gender', models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'F')], default='F', max_length=1, verbose_name='Gender')),
                ('api_pk', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='heroes.Heroes')),
                ('intelligence', models.PositiveIntegerField(null=True)),
                ('strength', models.PositiveIntegerField(null=True)),
                ('speed', models.PositiveIntegerField(null=True)),
                ('durability', models.PositiveIntegerField(null=True)),
                ('power', models.PositiveIntegerField(null=True)),
                ('combat', models.PositiveIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='heroes',
            name='powers',
            field=models.ManyToManyField(to='heroes.Power'),
        ),
        migrations.AddField(
            model_name='heroes',
            name='weaknesses',
            field=models.ManyToManyField(to='heroes.Weakness'),
        ),
    ]
